Projeto de Mercado Financeiro

Etapas:
1) Importar as bibliotecas yfinance, pandas, datetime e plotly.
2) Importar os indices do yfinance IBOVESPA, DOLAR
4) Colocar no gráfico todos indices e fazer a correlação.
5) Analisar periodo da pandemia.

In [2]:
import yfinance as yf
import pandas as pd
from datetime import datetime
import plotly.graph_objects as go
from plotly.subplots import make_subplots

data_inicio = '2000-01-01'
data_fim = '2026-12-31'

indices = ['^BVSP', 'BRL=X']

def pegar_cotacoes(lista_tickers, data_inicio, data_fim):
    df = yf.download(
        lista_tickers,
        start=data_inicio,
        end=data_fim,
        auto_adjust=False
    )
    df = df['Adj Close']
    df = df.ffill()
    return df

lista_ticker = indices
df_cotacoes = pegar_cotacoes(lista_ticker, data_inicio, data_fim)
display(df_cotacoes)

[*********************100%***********************]  2 of 2 completed

Ticker       BRL=X     ^BVSP
Date
2000-01-03     NaN   16930.0
2000-01-04     NaN   15851.0
2000-01-05     NaN   16245.0
2000-01-06     NaN   16107.0
2000-01-07     NaN   16309.0
...            ...       ...
2026-08-12  5.1735  167491.0
2026-08-13  5.1954  167101.0
2026-08-14  5.1998  166934.0
2026-08-17  5.2217  166934.0
2026-08-18  5.2008  166934.0

[6869 rows x 2 columns]

In [3]:
df_grafico = df_cotacoes[['^BVSP', 'BRL=X']].dropna()

grafico = make_subplots(specs=[[{"secondary_y": True}]])

grafico.add_trace(go.Scatter(
    x=df_grafico.index,
    y=df_grafico['^BVSP'],
    name='IBOVESPA'
), secondary_y=False)

grafico.add_trace(go.Scatter(
    x=df_grafico.index,
    y=df_grafico['BRL=X'],
    name='Dólar'
), secondary_y=True)

grafico.update_layout(
    template='plotly_dark',
    title='IBOVESPA x Dólar - Preços reais',
    hovermode='x unified'
)

grafico.update_yaxes(
    title_text='IBOVESPA',
    secondary_y=False
)

grafico.update_yaxes(
    title_text='Dólar BRL',
    secondary_y=True
)

grafico.show()

In [10]:
# Periodo da pandemia
data_pandemia = '2020-01-01'
fim_pandemia = '2020-12-31'

df_cotacoes = pegar_cotacoes(lista_ticker, data_pandemia, fim_pandemia)
display(df_cotacoes)

[*********************100%***********************]  2 of 2 completed

Ticker         BRL=X     ^BVSP
Date
2020-01-01  4.016786       NaN
2020-01-02  4.016300  118573.0
2020-01-03  4.023400  117707.0
2020-01-06  4.057000  116878.0
2020-01-07  4.060400  116662.0
...              ...       ...
2020-12-24  5.215300  117857.0
2020-12-25  5.215300  117857.0
2020-12-28  5.215300  119051.0
2020-12-29  5.245900  119475.0
2020-12-30  5.208600  119306.0

[261 rows x 2 columns]

In [12]:
df_pandemia = df_cotacoes[['^BVSP', 'BRL=X']].dropna()
grafico = make_subplots(specs=[[{"secondary_y": True}]])

grafico.add_trace(go.Scatter(
    x=df_pandemia.index,
    y=df_pandemia['^BVSP'],
    name='IBOVESPA'
), secondary_y=False)

grafico.add_trace(go.Scatter(
    x=df_pandemia.index,
    y=df_pandemia['BRL=X'],
    name='Dólar'
), secondary_y=True)

grafico.update_layout(
    template='plotly_dark',
    title='IBOVESPA x Dólar - Durante a pandemia - 2020',
    hovermode='x unified'
)

grafico.update_yaxes(
    title_text='IBOVESPA',
    secondary_y=False
)

grafico.update_yaxes(
    title_text='Dólar BRL',
    secondary_y=True
)

grafico.show()

In [13]:
df_pandemia = df_cotacoes[['^BVSP', 'BRL=X']].dropna()

ibov_inicio = df_pandemia['^BVSP'].iloc[0]
ibov_minimo = df_pandemia['^BVSP'].min()
data_ibov_minimo = df_pandemia['^BVSP'].idxmin()

dolar_inicio = df_pandemia['BRL=X'].iloc[0]
dolar_maximo = df_pandemia['BRL=X'].max()
data_dolar_maximo = df_pandemia['BRL=X'].idxmax()

queda_ibov = (ibov_minimo / ibov_inicio - 1) * 100
alta_dolar = (dolar_maximo / dolar_inicio - 1) * 100

print(f"Ibovespa caiu {queda_ibov:.2f}% até {data_ibov_minimo.date()}")
print(f"Dólar subiu {alta_dolar:.2f}% até {data_dolar_maximo.date()}")

Ibovespa caiu -46.39% até 2020-03-23
Dólar subiu 46.56% até 2020-05-14